# Generated by Django 5.2 on 2026-04-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Например: 'Доступ к веб-серверу'", max_length=100, verbose_name='Название правила')),
                ('source_ip', models.CharField(help_text='Формат: 192.168.1.0/24', max_length=500, verbose_name='Исходный IP / Маска')),
                ('dest_ip', models.CharField(help_text='Формат: 10.0.0.5/32', max_length=50, verbose_name='Целевой IP / Маска')),
                ('port', models.IntegerField(blank=True, help_text='Оставьте пустым для всех портов', null=True, verbose_name='Порт')),
                ('protocol', models.CharField(choices=[('TCP', 'TCP'), ('UDP', 'UDP'), ('ICMP', 'ICMP'), ('ANY', 'Any Protocol')], default='ANY', max_length=10, verbose_name='Протокол')),
                ('action', models.CharField(choices=[('ALLOW', 'Allow (Разрешить)'), ('DENY', 'Deny (Запретить)')], max_length=10, verbose_name='Действие')),
                ('is_redundant', models.BooleanField(default=False, help_text='Указывает, перекрывается ли это правило другим', verbose_name='Избыточность')),
                ('is_shadowed', models.BooleanField(default=False, help_text='Указывает на логический конфликт с правилом выше', verbose_name='Ошибка')),
                ('recommendation', models.TextField(blank=True, null=True, verbose_name='Рекомендация по оптимизации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Правило МСЭ',
                'verbose_name_plural': 'Правила МСЭ',
                'ordering': ['id'],
            },
        ),
    ]
