# Generated by Django 5.2 on 2026-04-12 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('import_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Загруженный файл',
                'verbose_name_plural': 'Загруженные файлы',
                'ordering': ['-import_date'],
            },
        ),
        migrations.AlterField(
            model_name='firewallrule',
            name='source_ip',
            field=models.CharField(help_text='Формат: 192.168.1.0/24', max_length=50, verbose_name='Исходный IP / Маска'),
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='file_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.fileimport', verbose_name='Источник (файл)'),
        ),
    ]
