# Generated by Django 5.2 on 2026-04-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fileimport_alter_firewallrule_source_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewallrule',
            name='is_correlated',
            field=models.BooleanField(default=False, verbose_name='Корреляция'),
        ),
    ]
