# Generated by Django 5.2 on 2026-04-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_firewallrule_is_correlated'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileimport',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
