# Generated by Django 5.2.7 on 2026-04-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fileimport_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firewallrule',
            name='is_correlated',
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='is_error',
            field=models.BooleanField(default=False, verbose_name='Ошибка'),
        ),
        migrations.AlterField(
            model_name='firewallrule',
            name='is_shadowed',
            field=models.BooleanField(default=False, help_text='Указывает на логический конфликт с правилом выше', verbose_name='Затенение'),
        ),
    ]
