# Generated by Django 5.2.7 on 2026-04-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_firewallrule_is_correlated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileimport',
            name='vendor',
            field=models.CharField(choices=[('GENERIC', 'Стандартный (CSV/JSON)'), ('USERGATE', 'UserGate (Export JSON)'), ('CONTINENT', 'МЭ Континент (XML)'), ('INFOTECS', 'ИнфоТеКС (VIPNet)')], default='GENERIC', max_length=20, verbose_name='Производитель'),
        ),
    ]
