# Generated by Django 5.2.7 on 2026-04-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_fileimport_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileimport',
            name='vendor',
            field=models.CharField(choices=[('STANDARD', 'Стандартный (CSV/JSON)'), ('USERGATE', 'UserGate (Export JSON)'), ('CONTINENT', 'МЭ Континент (XML)'), ('INFOTECS', 'ИнфоТеКС (VIPNet)')], default='STANDARD', max_length=100, verbose_name='Производитель'),
        ),
    ]
