# Generated by Django 5.2.7 on 2026-04-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_fileimport_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewallrule',
            name='port_end',
            field=models.IntegerField(default=65535),
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='port_start',
            field=models.IntegerField(default=0),
        ),
    ]
